export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const SEARCH_ARTICLE_BY_INPUT = 'SEARCH_ARTICLE_BY_INPUT';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const COLLAPSE_DRAWER = 'COLLAPSE_DRAWER';
export const SORT_ARTICLE_BY = 'SORT_ARTICLE_BY';